name: Build
on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    - cron: '30 3 * * 0'

env:
  TAG: ${{ github.ref }}

jobs:
  
  # Windows Builds on Windows Server 2019
  windows_build:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2
     
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
     
      - name: Setup Python Modules
        run: |
         pip install pyinstaller
         pip install pillow
     
      # Configure project with cmake
      - name: Build
        run: |
         pyinstaller -F nii.py
     
      - name: Prepare for Deploy
        shell: bash
        id: before_deploy
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          if [[ "${TAG:5:4}" == "tags" ]]; then export TAG=${TAG:10}; else export TAG=${COMMIT_SHA}; fi
          cd dist
          mkdir upload
          7z a upload/nii-${LABEL}-${TAG}.zip nii.exe
          echo ::set-output name=binary_path::upload
          echo ::set-output name=artifact_name::nii-${LABEL}-${TAG}.zip
          echo ::set-output name=file_name::nii-${LABEL}-${TAG}.zip
      
      # Upload to GH Release
      - name: Upload to GH Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/upload/${{ steps.before_deploy.outputs.file_name }}
          asset_name: ${{ steps.before_deploy.outputs.file_name }}
          asset_content_type: application/zip

      # Upload to GH Actions Artifacts
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.before_deploy.outputs.artifact_name }}
          path: ./dist/${{ steps.before_deploy.outputs.binary_path }}
